title: Ayanamibing
author: ayanamibing
email: ayanamibing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision Enthusiast
baseurl: "/jekyll-theme-kagami"
lang: en # site language  (en/ja/zh-Hans/zh-Hant)
color_scheme: tango # this specifies color scheme for syntax highlighting

mathjax: true

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock