title: 同年而语eth额头特额头恶化呢体验宝宝呢他也不能 额头有呢他
author: 不如一年也太难听你同意女人而言
email: your-email@domain.com
description: 让他女人干活的    额头热过渡大纲个
baseurl: "/热她和我他会突然他人人嗯而已呢额 agami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: kamikat

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
